### ISSUE TITLE
Local Fonts

### ISSUE THREAD

**Issue by Doc73** [flathub/org.onlyoffice.desktopeditors#2]
Dear Mantainers,
thank you very much for your efforts to port this app into FlatHub.
I would suggest an improvement, if possibile.
Is it possible to add at least the path of users fonts, usually installed in `~/.fonts` or in `~/.local/share/fonts`?

Thank you very much in advance,
Doc

**Comment by MrSenshi** [comment]
These commands allow you to move your system fonts into the flatpak runtime. I've used them and can confirm they work. You may have to change the commands slightly as this applies to version "19.08" of "org.freedesktop.Platform".

> sudo cp -r ~/.fonts/* /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/active/files/share/fonts/
> sudo cp -r /usr/share/fonts/* /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/active/files/share/fonts/

Hope this helps!

**Comment by TingPing** [comment]
Flatpak already grants access to fonts. If it doesn't its a bug and should be reported against flatpak.

Never copy paste random files into the flatpak, that should be obvious.

**Comment by TingPing** [comment]
The problem is *possibly* that this application bundles fontconfig which is broken. Just a thought though.

**Comment by dlalinsp** [comment]
> Flatpak already grants access to fonts. If it doesn't its a bug and should be reported against flatpak.

This can not be an issue with Flatpak as I've installed LibreOffice through Flathub and it can access those fonts.

**Comment by konradmb** [comment]
> The problem is _possibly_ that this application bundles fontconfig which is broken. Just a thought though.

@TingPing Looks like they're not using fontconfig paths. There are a couple of hardcoded paths in native server: https://github.com/ONLYOFFICE/core/blob/e1fa9b5c46cfdd220e478805f89d68a07288aeed/DesktopEditor/fontengine/ApplicationFonts.cpp#L1632

As Flatpak exposes system fonts inside `/run/host/fonts`, they're not available.
@ShockwaveNN Would you like to fix it upstream? This is fontconfig file included by Flatpak, so ideally those paths should be added (apart from `/run/host/fonts`): https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/files/fontconfig-flatpak.conf

**Comment by ShockwaveNN** [comment]
> @ShockwaveNN Would you like to fix it upstream?

Sorry, I'm a QA guy, I can only ask @agolybev or his team to fix it

**Comment by ShockwaveNN** [comment]
Our dev team fixed this problem at here https://github.com/ONLYOFFICE/core/pull/469

This fix we hope will be available in next major release, v6.2.0

**Comment by ShockwaveNN** [comment]
I think this problem should be fixed in current stable release of fltapak, if someone still have troubles please confirm this

**Comment by ShockwaveNN** [comment]
Closing this issue since seems this is should be resolved

**Comment by Peter4487** [comment]
I believe this is still a problem in 7.0.0.127 flatpak in the Presentation editor. When I create a text box and then go to the "Home" tab, the drop-down for typefaces doesn't work. It doesn't display a drop-down when the little down-arrow is clicked, a little bubble saying "font" shows up though.

When I type the name of a font I know I have in the box (e.g., Liberation Serif), a popup appears:
![image](https://user-images.githubusercontent.com/56004444/152610115-f5665ccc-2b13-472e-9bcc-8315a9ac9a2b.png)

When I select yes it does something to the typeface, can't tell by eye if it's going for closest or actually getting the one I select somehow.

**Comment by ShockwaveNN** [comment]
@Peter4487 I think it's separate issue from original one

>  the drop-down for typefaces doesn't work

This is not right and some fonts should be present in any cases

I think it's better to create a new issue and add details about your host os
